# Generated by Django 5.1.7 on 2025-05-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slides',
            name='image_url',
        ),
        migrations.AddField(
            model_name='slides',
            name='image',
            field=models.ImageField(default=0, upload_to='slides/'),
            preserve_default=False,
        ),
    ]
